llm:
  model: llama3
  temperature: 0.3
  top_k: 50
  top_p: 0.9
  repeat_penalty: 1.1

embeddings:
  model_name: sentence-transformers/all-MiniLM-L6-v2

csv:
  separator: ";"
  max_file_size_mb: 5
  encodings:
    - utf-8
    - utf-16
    - ISO-8859-1

retriever:
  top_k: 3
